antalya-general:
  city_value: "Antalya"
  office_value: "Antalya Ofis"
  getapplicationtype: "Genel"
  office_type: ["STANDART", "PREMIUM LOUNGE"] # You can provide multiple office types or just one like below
  telegram_token: "TELEGRAM_TOKEN_ANTALYA_GENERAL"
  telegram_chat_id: "TELEGRAM_CHAT_ID"

ankara-general:
  city_value: "Ankara"
  office_value: "Ankara Ofis"
  getapplicationtype: "Diğer"
  office_type: "STANDART" # You can also provide just one office type as string
  telegram_token: "TELEGRAM_TOKEN_ANKARA_GENERAL"
  telegram_chat_id: "TELEGRAM_CHAT_ID"

ankara-education:
  city_value: "Ankara"
  office_value: "Ankara Ofis"
  getapplicationtype: "Eğitim"
  office_type: ["STANDART", "PREMIUM LOUNGE"]
  telegram_token: "TELEGRAM_TOKEN_ANKARA_EDUCATION"
  telegram_chat_id: "TELEGRAM_CHAT_ID"