antalya-general:
  city_value: "Antalya"
  office_value: "Antalya Ofis"
  getapplicationtype: "Genel"
  telegram_token: "TELEGRAM_TOKEN_ANTALYA_GENERAL"
  telegram_chat_id: "TELEGRAM_CHAT_ID"

ankara-general:
  city_value: "Ankara"
  office_value: "Ankara Ofis"
  getapplicationtype: "Diğer"
  telegram_token: "TELEGRAM_TOKEN_ANKARA_GENERAL"
  telegram_chat_id: "TELEGRAM_CHAT_ID"

ankara-education:
  city_value: "Ankara"
  office_value: "Ankara Ofis"
  getapplicationtype: "Eğitim"
  telegram_token: "TELEGRAM_TOKEN_ANKARA_EDUCATION"
  telegram_chat_id: "TELEGRAM_CHAT_ID"